apiVersion: v1
kind: Pod
metadata:
  name: user-service
  labels:
    name: user-service
spec:
  containers:
    - name: user
      image: user
      ports:
        - containerPort: 10086

      imagePullPolicy: IfNotPresent
    - name: mysql
      image: mysql-for-user
      ports:
        - containerPort: 3308
      env:
        - name: MYSQL_ROOT_PASSWROD
          value: "root"
      imagePullPolicy: IfNotPresent
    - name: redis
      image: redis:5.0
      ports:
        - containerPort: 6378
      imagePullPolicy: IfNotPresent
