apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    name: user-service
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: user-service
  template:
    metadata:
      labels:
        name: user-service
    spec:
      containers:
        - name: user
          image: user
          ports:
            - containerPort: 10086
          imagePullPolicy: IfNotPresent
        - name: mysql
          image: mysql-for-user
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          imagePullPolicy: IfNotPresent
        - name: redis
          image: redis:5.0
          ports:
            - containerPort: 6379
          imagePullPolicy: IfNotPresent
